declare component Translate(t, di, do, c): in -> out

sequence toe_in = ?N : <t>
sequence data_in = ?N : <di>
sequence toe_out = ?N : <t>
sequence data_out = ?N : <do>

sequence in = toe_in data_in : <t+di>
sequence out = toe_out data_out : <t+do>

strand In = in : <t+di>
strand Base = ?N : <t+di>
strand Out = <di-t-c>N out : <di + do - c>

## Structures
structure IN = In : U<t+di>
structure Gate = Out + Base : H<di>(U<do-c> +) U<t>

structure IN_waste = In + Base : H<t+di>(+)
structure OUT = Out : U<di+do-c>

kinetic IN + Gate -> OUT + IN_waste
