declare component DAOtileS: LL + LR -> UL + UR

## should just be 
## import DAOtileR
## component S = DAOtileR: UL* + UR* -> LL* + LR*


## sticky end sequences
sequence LL = 5N
sequence UL = 5N
sequence LR = 5N
sequence UR = 5N

## core sequences
sequence ULarm = S 7N 
sequence Ucore = S 14N S
sequence URarm = 7N S
sequence LLarm = S 7N 
sequence Lcore = S 14N S
sequence LRarm = 7N S

## Strands
strand longLeft   = ULarm Ucore Lcore* LLarm*
strand longRight  = URarm* Ucore* Lcore LRarm
strand shortLeft  = LL LLarm ULarm* UL*
strand shortRight = LR LRarm* URarm UR*
