declare component DAOtileR: LL + LR -> UL + UR

## Sequences
# sticky ends
sequence LL = 5N 
sequence UL = 5N 
sequence LR = 5N 
sequence UR = 5N 

# core 
sequence ULarm = S 7N : 8
sequence Ucore = S 14N S : 16
sequence URarm = 7N S : 8 
sequence LLarm = S 7N : 8 
sequence Lcore = S 14N S : 16
sequence LRarm = 7N S : 8

## Strands
strand longLeft   = LLarm Lcore Ucore* ULarm*
strand longRight  = LRarm* Lcore* Ucore URarm
strand shortLeft  = UL* ULarm LLarm* LL
strand shortRight = UR* URarm* LRarm LR

