declare component DAOtileS: sLL + sLR -> sUL + sUR

## should just be 
## import DAOtileR
## component S = DAOtileR: sUL* + sUR* -> sLL* + sLR*


## sticky end sequences
sequence sLL = 5N : 5
sequence sUL = 5N : 5
sequence sLR = 5N : 5
sequence sUR = 5N : 5

## core sequences
sequence sULarm = S 7N :8
sequence sUcore = S 14N S : 16
sequence sURarm = 7N S : 8
sequence sLLarm = S 7N : 8
sequence sLcore = S 14N S : 16
sequence sLRarm = 7N S : 8

## Strands
strand longLeft   = sULarm sUcore sLcore* sLLarm* : 48
strand longRight  = sURarm* sUcore* sLcore sLRarm : 48
strand shortLeft  = sLL sLLarm sULarm* sUL* : 26
strand shortRight = sLR sLRarm* sURarm sUR* : 26

# Dummy structures
structure [no-opt] LongLeft = longLeft : U48
structure [no-opt] LongRight = longRight : U48
structure [no-opt] ShortLeft = shortLeft : U26
structure [no-opt] ShortRight = shortRight : U26
