declare component Catalyst: cat -> sb + ob + cat

## Sequences
sequence r1  = "4N" : 4
sequence r2  = "4N" : 4
sequence r3  = "4N" : 4
sequence r4  = "4N" : 4
sequence r5  = "4N" : 4
sequence r6  = "4N" : 4
sequence r10 = "4N" : 4

## Strands
# Inputs
strand fuel = r2 r3 r4
strand cat  = r4 r5
# Gate sections
strand lb = r5* r4* r3* r2*
strand ob = r1  r2
strand sb = r6  r3  r4

## Structures/Complexes
# Input
structure Fuel = fuel : domain ...
structure Cat  = cat  : domain ..
# Gate (and Intermediate structures)
structure S  = lb + ob + sb  : domain .(((+.)+.))
structure I3 = lb + ob + cat : domain ((.(+.)+))
# Outputs
structure SB = sb : domain ...
structure OB = ob : domain ..
# Waste
structure Waste = lb + fuel : domain .(((+)))

## Kinetics
# Overall: Cat + S + Fuel  ->  SB + OB + Cat + Waste
kinetic Cat  + S  ->  SB + I3
kinetic Fuel + I3 ->  OB + Waste + Cat

